networks:
  app-network:
    driver: bridge
    
services:
  test-web:
    container_name: test-web
    restart: always
    build:
      context: .
      dockerfile: TestSPS.Web/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - test-api

  test-api:
    container_name: test-api
    restart: always
    build:
      context: .
      dockerfile: TestSPS.Api/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - test-sqlserver
      
  test-sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: test-sqlserver
    restart: always
    ports:
        - 8002:1433
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=myStong_Password123#
    networks:
      - app-network
