networks:
  app-network:
    driver: bridge
    
volumes:
  test-mssql-data:

services:
  test-web:
    container_name: test-web
    build:
      context: .
      dockerfile: TestSPS.Web/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - test-api

  test-api:
    container_name: test-api
    build:
      context: .
      dockerfile: TestSPS.Api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - test-sqlserver
      
  test-sqlserver:
    container_name: test-sqlserver
    build:
      context: .
      dockerfile: sql/Dockerfile
    ports:
        - 8002:1433
    volumes:
      - test-mssql-data:/var/opt/mssql
    networks:
      - app-network
